name: deploy

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform Plan
        uses: ./.github/workflows/terraform-plan-pipeline-ci.yml
      - name: Terraform Apply
        uses: ./.github/workflows/terraform-apply-pipeline-ci.yml
